name: docs

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: testing this input
        required: true
        default: 'test'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROD: true

    steps:
    - name: Something
      run: |
        TEST=HAHA
        echo "TEST1=${{ true && env.PROD == 'true' && format('{0}/test', env.PROD) || 'dev' || 'haha' }}" >> $GITHUB_ENV
   
    - name: something test
      run: echo "${{ github.event.inputs.test_input }}"
    - name: Something 2
      run: echo ${{ env.TEST1 }}
      
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    # Grabbing custom dependencies and building as a pdf.
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
        build-command: "make latexpdf"
        docs-folder: "docs/"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    # Create an artifact out of the previously built pdf.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationPDF
        path: docs/_build/latex/distributedfinder.pdf
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/Diaga/Distributed-Finder.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
